name: Deploy to Remote Branch

on:
  push:
    branches:
      - master
      
jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GITHUB_REMOTE_REPOSITORY: "sermonarchives/sermonarchives.github.io"
        GITHUB_BRANCH: master
        GIT_DEPLOY_KEY: ${{ secrets.HUGO }}
        HUGO_VERSION: "0.68.3"
